name: flutter_specialist_start
description: A new Flutter project.

publish_to: 'none'



environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  flutter_modular: ^5.0.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter:

 
  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts//barlow/Barlow-Black.ttf
        - asset: assets/fonts//barlow/Barlow-BlackItalic.ttf
        - asset: assets/fonts//barlow/Barlow-Bold.ttf
        - asset: assets/fonts//barlow/Barlow-BoldItalic.ttf
        - asset: assets/fonts//barlow/Barlow-ExtraBold.ttf
        - asset: assets/fonts//barlow/Barlow-ExtraLight.ttf
        - asset: assets/fonts//barlow/Barlow-ExtraLightItalic.ttf
        - asset: assets/fonts//barlow/Barlow-ExtraLight.ttf
        - asset: assets/fonts//barlow/Barlow-Italic.ttf
        - asset: assets/fonts//barlow/Barlow-Light.ttf
        - asset: assets/fonts//barlow/Barlow-LightItalic.ttf
        - asset: assets/fonts//barlow/Barlow-Medium.ttf
        - asset: assets/fonts//barlow/Barlow-MediumItalic.ttf
        - asset: assets/fonts//barlow/Barlow-Regular.ttf
        - asset: assets/fonts//barlow/Barlow-Thin.ttf
        - asset: assets/fonts//barlow/Barlow-ThinItalic.ttf
          weight: 700 
    - family: Dosis
      fonts:
        - asset: assets/fonts//dosis/Dosis-Bold.ttf
        - asset: assets/fonts//dosis/Dosis-ExtraBold.ttf
        - asset: assets/fonts//dosis/Dosis-ExtraLight.ttf
        - asset: assets/fonts//dosis/Dosis-Light.ttf
        - asset: assets/fonts//dosis/Dosis-Medium.ttf
        - asset: assets/fonts//dosis/Dosis-Regular.ttf
        - asset: assets/fonts//dosis/Dosis-SemiBold.ttf
          weight: 700 
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
